id: IB65BAAD8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T15:50:46+00:00'
last_modified: '2022-06-07T15:07:11.207535+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18573
  title: ལང་ཚོའི་ཉམས་འགྱུར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    407A:
      image_group_id: I1KG18666
      title: ''
      total_pages: 140
      order: 1
      base_file: 407A.txt
    048A:
      image_group_id: I1KG18667
      title: ''
      total_pages: 116
      order: 2
      base_file: 048A.txt
    9F3D:
      image_group_id: I1KG20846
      title: ''
      total_pages: 110
      order: 3
      base_file: 9F3D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
