id: P001778
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18573
  title: ལང་ཚོའི་ཉམས་འགྱུར།
  author: ''
  volumes:
    c0aa813983c74acfb74665db2dc849a6:
      image_group_id: I1KG18666
      title: ''
      volume_number: 1
      total_pages: 140
    3f489a690848457fa1aabdaab3d72d2a:
      image_group_id: I1KG18667
      title: ''
      volume_number: 2
      total_pages: 116
    d104b2523fca4b90a428243ce69fe721:
      image_group_id: I1KG20846
      title: ''
      volume_number: 3
      total_pages: 110
